[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino

monitor_speed = 115200
upload_speed = 115200

board_build.flash_mode = dio
board_build.f_flash = 80000000L
board_build.flash_size = 4MB
board_build.partitions = default.csv

lib_deps =
  h2zero/NimBLE-Arduino@1.4.3

build_flags =
  -D CONFIG_BT_NIMBLE_ROLE_PERIPHERAL=0
  -D CONFIG_BT_NIMBLE_ROLE_BROADCASTER=0
  -D CONFIG_BT_NIMBLE_ROLE_OBSERVER=1
  -D CONFIG_BT_NIMBLE_ROLE_CENTRAL=1
  -D CONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
  -D CONFIG_NIMBLE_CPP_LOG_LEVEL=0
